### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by timosachsenberg** [OpenMS/openms.de#11]
- not sure if I like having the latest news item "SECOND OPENMS DOCUMENTATION UPDATE" on the top.  For me it was hard to tell that this is a news item.
- having OpenMS + the OpenMS logo is a bit redundant. Would having only the logo be better in our case? As it writes out the name anyway
- Maybe write "The open-source framework for Mass Spectrometry" instead of "The fundamental software for Mass Spectometry" (also note the typo)
- What about the "Features" heading? Is this needed or a placeholder?
- The "Metabolomics" image shows DNA. Maybe we should use something that is better associated with Metabolites (e.g., the molecule icon on the old homepage nails that better).
- Do we have links to the license statements of all used images? (Sometimes images show up in google search as "free to use" while in reality they are copyrighted.)

**Comment by rahul799** [comment]
- [ ] not sure if I like having the latest news item "SECOND OPENMS DOCUMENTATION UPDATE" on the top. For me it was hard to tell that this is a news item.

- [ ] having OpenMS + the OpenMS logo is a bit redundant. Would having only the logo be better in our case? As it writes out the name anyway

- [ ] Maybe write "The open-source framework for Mass Spectrometry" instead of "The fundamental software for Mass Spectometry" (also note the typo)

- [ ] What about the "Features" heading? Is this needed or a placeholder?

- [ ] The "Metabolomics" image shows DNA. Maybe we should use something that is better associated with Metabolites (e.g., the molecule icon on the old homepage nails that better).

- [ ] Do we have links to the license statements of all used images? (Sometimes images show up in google search as "free to use" while in reality they are copyrighted.)

**Comment by enetz** [comment]
a question about the three images:
the text is not aligned between the boxes, so it depends on the size of the images? So we will need three images of the exact same height to keep the text symmetrical.

And I think this was mentioned before, but the python logo looks unnecessarily large

**Comment by rahul799** [comment]
@enetz @timosachsenberg  as per the discussion, I have added the old layout. I think all of the above points are now addressed. Can we close this issue now?

**Comment by timosachsenberg** [comment]
- [ ] like old design of quick facts better
- [ ] like old design of pyOpenMS better

**Comment by rahul799** [comment]
Yes, for that we already have another issue #40 🥲

**Comment by timosachsenberg** [comment]
haha sorry.
